# Creation of Array

In [1]:
#Exp no:5

In [2]:
#Aim:To perform Creation of Array using Numpy

In [3]:
#Name:Tanvi Gajanan Kacharde
#Roll no:25
#Sec:A
#Subject:ET1
#Date:19-08-2025

In [4]:
#importing the basic library
import numpy as np

In [22]:
# Creating 1D Array Using Numpy

In [23]:
a1=np.array([10,20,30,40,50])

In [24]:
a1

array([10, 20, 30, 40, 50])

In [25]:
# Creating 2D Array Using Numpy

In [26]:
a2=np.array([[10,20,30,40,50],[60,70,80,90,100]])

In [27]:
a2

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [28]:
a3=np.matrix('11 22;33 44;55 66')
print(a3)

[[11 22]
 [33 44]
 [55 66]]
